version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass admin
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
